Refactor customize_iso script after changes in Arch Linux installation ISO layout

diff --git a/hal/bin/customize_iso b/hal/bin/customize_iso
--- a/hal/bin/customize_iso
+++ b/hal/bin/customize_iso
@@ -1,265 +1,59 @@
-#!/bin/bash
-#===============================================================================
+#!/usr/bin/bash
+#-------------------------------------------------------------------------------
 # FILE:         customize_iso
 #
-# USAGE:        ./customize_iso
+# USAGE:        Run 'customize_iso -h' for more details
 #
 # DESCRIPTION:  Creates ISO based on provided Arch Linux ISO,
 #               adding provided custom content
-#
-# TODO:         Add switch to chose i686 or/and x86_64 architecture
-#===============================================================================
-
-# Setup shell - detect unset variables
-set -o nounset
+#-------------------------------------------------------------------------------
 
 #-------------------------------------------------------------------------------
 # Settings adjustable using command line options
 #-------------------------------------------------------------------------------
 
-ORIGINAL_ISO="~/shared/archlinux-2014.08.01-dual.iso"
-NEW_ISO="~/shared/custom-archlinux-2014.08.01-dual.iso"
-WORKSPACE="~/forge/customize_iso"
-CUSTOM_SRC="~/bin"
-CUSTOM_DST="/root"
-
-#-------------------------------------------------------------------------------
-# Settings adjustable by editing this script
-#-------------------------------------------------------------------------------
-
-ISO_MNT_PNT="/mnt/iso"
-FS_MNT_PNT="/mnt/iso_rootfs"
-
-#-------------------------------------------------------------------------------
-# Not editable (unless changed in Arch Linux)
-#-------------------------------------------------------------------------------
-
-PACKAGES="squashfs-tools cdrkit"
-SFS_NAME="airootfs.sfs"
-MD5_NAME="airootfs.md5"
-IMG_NAME="airootfs.img"
-USQ_NAME="squashfs-root"
+ORIGINAL_ISO=                           # To be provided by user
+NEW_ISO=                                # To be provided by user
+WORKSPACE="/tmp/${0##*/}"               # Use name of the script for dir name
+CUSTOM_SRC="/home/adam/archon/hal/bin"
+CUSTOM_DST="root"
 
 #-------------------------------------------------------------------------------
 # Functions
 #-------------------------------------------------------------------------------
 
-updatePackageList()
+usage()
 {
-    echo "Update package list..."
-    sudo pacman -Syy
-    echo "Update package list...done"
+cat << EOF
+Creates ISO based on provided Arch Linux ISO, adding provided custom content
+Requires squashfs-tools and cdrkit packages
+
+Usage: ${0##*/} [-h] [-o ORIG_ISO] [-n NEW_ISO] [-w WORKSPACE] [-s SRC] [-d DST]
+    -h display this help and exit
+    -o ORIG_ISO original ISO file (${ORIGINAL_ISO:-"unset"})
+    -n NEW_ISO ISO file to be created (${NEW_ISO:-"unset"})
+    -w WORKSPACE dir for temporary files (${WORKSPACE:-"unset"})
+    -s SRC source dir with ISO customization content (${CUSTOM_SRC:-"unset"})
+    -d DST dir where customization content will be available after booting ISO \
+(${CUSTOM_DST:-"unset"})
+EOF
 }
 
-checkPackages()
+checkOptions()
 {
-    echo "Check packages..."
+    if [[ -z "$ORIGINAL_ISO" ]]; then
+        echo "Unset parameter ORIG_ISO, use option -o"
+        echo
+        usage
+        exit 1
+    fi
 
-    for pkg in $PACKAGES
-    do
-        pacman -Qsq $pkg &>/dev/null
-        if [[ "$?" -ne 0 ]]; then
-            eval "sudo pacman -S --noconfirm $pkg"
-        fi
-    done
-
-    echo "Check packages...done"
-}
-
-createIsoMountPoint()
-{
-    echo "Create ISO mount point..."
-    eval "sudo mkdir -p $ISO_MNT_PNT"
-    echo "Create ISO mount point...done"
-}
-
-removeIsoMountPoint()
-{
-    echo "Remove ISO mount point..."
-    eval "sudo rmdir $ISO_MNT_PNT"
-    echo "Remove ISO mount point...done"
-}
-
-mountIso()
-{
-    echo "Mount ISO..."
-    eval "sudo mount -t iso9660 -o loop $ORIGINAL_ISO $ISO_MNT_PNT"
-    echo "Mount ISO...done"
-}
-
-unmountIso()
-{
-    echo "Unmount ISO..."
-    eval "sudo umount $ISO_MNT_PNT"
-    echo "Unmount ISO...done"
-}
-
-createWorkspaceDir()
-{
-    echo "Create workspace directory..."
-    eval "mkdir -p $WORKSPACE"
-    echo "Create workspace directory...done"
-}
-
-removeWorkspace()
-{
-    echo "Remove workspace..."
-    eval "rm -rf $WORKSPACE"
-    echo "Remove workspace...done"
-}
-
-copyIsoContents()
-{
-    echo "Copy ISO contents..."
-    eval "cp -a $ISO_MNT_PNT $ISO_CONTENTS_DIR"
-    echo "Copy ISO contents...done"
-}
-
-unsquashFs()
-{
-    echo "Unsquash file system..."
-
-    local newFsPath="$1"
-    local originalFsPath="$2"
-
-    eval "mkdir -p $newFsPath"
-    eval "cd $newFsPath"
-    eval "unsquashfs $originalFsPath/$SFS_NAME"
-
-    echo "Unsquash file system...done"
-}
-
-createFsImgMountPoint()
-{
-    echo "Create file systen image mount point..."
-    eval "sudo mkdir -p $FS_MNT_PNT"
-    echo "Create file systen image mount point...done"
-}
-
-removeFsImgMountPoint()
-{
-    echo "Remove file system image mount point..."
-    eval "sudo rmdir $FS_MNT_PNT"
-    echo "Remove file system image mount point...done"
-}
-
-mountFsImage()
-{
-    echo "Mount file system image..."
-    local newFsPath="$1"
-    eval "sudo mount $newFsPath/$USQ_NAME/$IMG_NAME $FS_MNT_PNT"
-    echo "Mount file system image...done"
-}
-
-unmountFsImage()
-{
-    echo "Unmount file sytem image..."
-    eval "sudo umount $FS_MNT_PNT"
-    echo "Unmount file sytem image...done"
-}
-
-copyCustomContent()
-{
-    echo "Copy custom content..."
-    eval "sudo cp -R $CUSTOM_SRC/* $FS_MNT_PNT$CUSTOM_DST"
-    echo "Copy custom content...done"
-}
-
-squashNewFs()
-{
-    echo "Squash new file system..."
-    local newFsPath="$1"
-    eval "mksquashfs $newFsPath/$USQ_NAME $newFsPath/$SFS_NAME"
-    echo "Squash new file system...done"
-}
-
-generateNewFsChecksum()
-{
-    echo "Generate new file system checksum..."
-    local newFsPath="$1"
-    eval "md5sum $newFsPath/$SFS_NAME > $newFsPath/$MD5_NAME"
-    echo "Generate new file system checksum...done"
-}
-
-removeOriginalFsFiles()
-{
-    echo "Remove original file sytem files..."
-    local originalFsPath="$1"
-    eval "rm $originalFsPath/$SFS_NAME"
-    eval "rm $originalFsPath/$MD5_NAME"
-    echo "Remove original file sytem files...done"
-}
-
-copyNewFsFiles()
-{
-    echo "Copy new file system files..."
-    local newFsPath="$1"
-    local originalFsPath="$2"
-    eval "cp $newFsPath/$SFS_NAME $originalFsPath/$SFS_NAME"
-    eval "cp $newFsPath/$MD5_NAME $originalFsPath/$MD5_NAME"
-    echo "Copy new file system files...done"
-}
-
-generateNewIso()
-{
-    echo "Generate new ISO..."
-    eval "cd $ISO_CONTENTS_DIR"
-    eval "genisoimage -l -r -J -V \"$ISO_VERSION\""\
-         "-b isolinux/isolinux.bin -no-emul-boot -boot-load-size 4"\
-         "-boot-info-table -c isolinux/boot.cat"\
-         "-o $NEW_ISO $ISO_CONTENTS_DIR"
-    echo "Generate new ISO...done"
-}
-
-prepareFileSystem()
-{
-    local newFsDir="$1"
-    local originalFsDir="$2"
-
-    unsquashFs $newFsDir $originalFsDir
-    createFsImgMountPoint
-    mountFsImage $newFsDir
-    copyCustomContent
-    unmountFsImage
-    removeFsImgMountPoint
-    squashNewFs $newFsDir
-    generateNewFsChecksum $newFsDir
-    removeOriginalFsFiles $originalFsDir
-    copyNewFsFiles $newFsDir $originalFsDir
-}
-
-prepareFileSystemX86_64()
-{
-    echo "Prepare x86_64 file system..."
-    prepareFileSystem $X86_64_FS_DIR $X86_64_FS_SRC
-    echo "Prepare x86_64 file system...done"
-}
-
-prepareFileSystemI686()
-{
-    echo "Prepare i686 file system..."
-    prepareFileSystem $I686_FS_DIR $I686_FS_SRC
-    echo "Prepare i686 file system...done"
-}
-
-createCustomIso()
-{
-    echo "Create custom ISO..."
-    updatePackageList
-    checkPackages
-    # Exit on error
-    set -o errexit
-    createIsoMountPoint
-    mountIso
-    createWorkspaceDir
-    copyIsoContents
-    unmountIso
-    removeIsoMountPoint
-    prepareFileSystemX86_64
-    prepareFileSystemI686
-    generateNewIso
-    removeWorkspace
-    echo "Create custom ISO...done"
+    if [[ -z "$NEW_ISO" ]]; then
+        echo "Unset parameter NEW_ISO, use option -n"
+        echo
+        usage
+        exit 1
+    fi
 }
 
 query()
@@ -283,25 +77,112 @@ query()
     esac
 }
 
-usage()
+createCustomIso()
 {
-cat << EOF
-Creates ISO based on provided Arch Linux ISO, adding provided custom content
+    echo "Create custom ISO..."
 
-Usage: ${0##*/} [-h] [-o ORIG_ISO] [-n NEW_ISO] [-w WORKSPACE] [-s SRC] [-d DST]
-    -h display this help and exit
-    -o ORIG_ISO original ISO file ($ORIGINAL_ISO)
-    -n NEW_ISO ISO file to be created ($NEW_ISO)
-    -w WORKSPACE dir for temporary files ($WORKSPACE)
-    -s SRC source dir with ISO customization content ($CUSTOM_SRC)
-    -d DST dir where customization content will be available after booting ISO
-       ($CUSTOM_DST)
-EOF
+    #----------------------------------------
+    # Extract original ISO contents
+    #----------------------------------------
+
+    echo "Create iso mount point..."
+    eval "sudo mkdir -p /mnt/customize_iso"
+
+    echo "Mount ISO..."
+    eval "sudo mount -t iso9660 -o loop $ORIGINAL_ISO /mnt/customize_iso"
+
+    echo "Create workspace directory..."
+    eval "mkdir -p $WORKSPACE"
+
+    echo "Copy ISO contents..."
+    eval "cp -a /mnt/customize_iso $WORKSPACE/iso_contents"
+
+    echo "Unmount ISO..."
+    eval "sudo umount /mnt/customize_iso"
+
+    echo "Remove ISO mount point..."
+    eval "sudo rmdir /mnt/customize_iso"
+
+    #----------------------------------------
+    # Prepare x86_64 file system
+    #----------------------------------------
+
+    echo "Unsquash x86_64 file system..."
+    eval "unsquashfs -u -d $WORKSPACE/x86_64_fs"\
+         "$WORKSPACE/iso_contents/arch/x86_64/airootfs.sfs"
+
+    echo "Copy custom x86_64 content..."
+    eval "sudo cp -R $CUSTOM_SRC/* $WORKSPACE/x86_64_fs/$CUSTOM_DST"
+
+    echo "Squash new x86_64 file system..."
+    eval "mksquashfs $WORKSPACE/x86_64_fs $WORKSPACE/airootfs.sfs -comp xz"
+
+    echo "Generate new x86_64 file system checksum..."
+    eval "md5sum $WORKSPACE/airootfs.sfs > $WORKSPACE/airootfs.md5"
+
+    echo "Remove original x86_64 file sytem files..."
+    eval "rm $WORKSPACE/iso_contents/arch/x86_64/airootfs.sfs"
+    eval "rm $WORKSPACE/iso_contents/arch/x86_64/airootfs.md5"
+
+    echo "Move new x86_64 file system files..."
+    eval "mv $WORKSPACE/airootfs.sfs $WORKSPACE/iso_contents/arch/x86_64"
+    eval "mv $WORKSPACE/airootfs.md5 $WORKSPACE/iso_contents/arch/x86_64"
+
+    #----------------------------------------
+    # Prepare i686 file system
+    #----------------------------------------
+
+    echo "Unsquash i686 file system..."
+    eval "unsquashfs -u -d $WORKSPACE/i686_fs"\
+         "$WORKSPACE/iso_contents/arch/i686/airootfs.sfs"
+
+    echo "Copy custom i686 content..."
+    eval "sudo cp -R $CUSTOM_SRC/* $WORKSPACE/i686_fs/$CUSTOM_DST"
+
+    echo "Squash new i686 file system..."
+    eval "mksquashfs $WORKSPACE/i686_fs $WORKSPACE/airootfs.sfs -comp xz"
+
+    echo "Generate new i686 file system checksum..."
+    eval "md5sum $WORKSPACE/airootfs.sfs > $WORKSPACE/airootfs.md5"
+
+    echo "Remove original i686 file sytem files..."
+    eval "rm $WORKSPACE/iso_contents/arch/i686/airootfs.sfs"
+    eval "rm $WORKSPACE/iso_contents/arch/i686/airootfs.md5"
+
+    echo "Move new i686 file system files..."
+    eval "mv $WORKSPACE/airootfs.sfs $WORKSPACE/iso_contents/arch/i686"
+    eval "mv $WORKSPACE/airootfs.md5 $WORKSPACE/iso_contents/arch/i686"
+
+    #----------------------------------------
+    # Generate new ISO
+    #----------------------------------------
+
+    echo "Generate new ISO..."
+    eval "cd $WORKSPACE/iso_contents"
+    eval "genisoimage -l -r -J -V \"$ISO_VERSION\""\
+         "-b isolinux/isolinux.bin -no-emul-boot -boot-load-size 4"\
+         "-boot-info-table -c isolinux/boot.cat"\
+         "-o $NEW_ISO $WORKSPACE/iso_contents"
+
+    #----------------------------------------
+    # Remove workspace
+    #----------------------------------------
+
+    echo "Remove workspace..."
+    eval "sudo rm -rf $WORKSPACE"
+    echo "Remove workspace...done"
+
+    echo "Create custom ISO...done"
 }
 
 #-------------------------------------------------------------------------------
 # Execution
 #-------------------------------------------------------------------------------
+
+if [[ "$#" -eq "0" ]]; then
+    usage
+    exit 0
+fi
 
 while getopts ":ho:n:w:s:d:" opt; do
     case $opt in
@@ -330,25 +211,25 @@ while getopts ":ho:n:w:s:d:" opt; do
             ;;
         :)
             echo "Option -$OPTARG requires an argument"
-            exit 2
+            exit 1
             ;;
     esac
 done
 
-#-------------------------------------------------------------------------------
+checkOptions
+
+#----------------------------------------
 # Dependent on command line options
-#-------------------------------------------------------------------------------
+#----------------------------------------
+
+# Setup shell - detect unset variables
+set -o nounset
+# Setup shell - exit on error
+set -o errexit
 
 ORIGINAL_NAME="${ORIGINAL_ISO##*/}"
 ISO_YEAR="${ORIGINAL_NAME:10:4}"
 ISO_MONTH="${ORIGINAL_NAME:15:2}"
 ISO_VERSION="ARCH_$ISO_YEAR$ISO_MONTH"
 
-ISO_CONTENTS_DIR="$WORKSPACE/iso_contents"
-X86_64_FS_DIR="$WORKSPACE/x86_64_fs"
-I686_FS_DIR="$WORKSPACE/i686_fs"
-X86_64_FS_SRC="$ISO_CONTENTS_DIR/arch/x86_64"
-I686_FS_SRC="$ISO_CONTENTS_DIR/arch/i686"
-
 query
-
